/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mainGUI;

import java.awt.FlowLayout;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author Ali
 */
public class TrainingJFrame extends javax.swing.JFrame {

    private ChartPanel chartPanel;
    private XYSeries series;
    private JFreeChart chart;
    private XYSeriesCollection seriesCollection;
        
    int i=0;
    
    private void initLineChartPanel() {
        series = new XYSeries("MSE");
        seriesCollection = new XYSeriesCollection(series);

        chart = ChartFactory.createXYLineChart("Training", "Epoch Number", "MSE", seriesCollection,PlotOrientation.VERTICAL,true,true,true);
        chartPanel = new ChartPanel(chart);
        chartPanel.setSize(chartContainerPanel.getWidth(), chartContainerPanel.getHeight());
        
        chartContainerPanel.add(chartPanel);
    }
    
    private void add(int i,double val){
        series.add(i, val);
    }
    
    /**
     * Creates new form TrainingJFrame
     */
    public TrainingJFrame() {
        initComponents();
        initLineChartPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chartContainerPanel = new javax.swing.JPanel();
        trainingPanel = new javax.swing.JPanel();
        netFileNameText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        autoSaveNetCheck = new javax.swing.JCheckBox();
        saveNetButton = new javax.swing.JButton();
        startStopTrain = new javax.swing.JButton();
        maxNumEpochText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        learningParamsPanel = new javax.swing.JPanel();
        learningRateText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        momentumText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        weightDecayText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        changeLearningParamsButton = new javax.swing.JButton();
        statusPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        epochNumLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lastMSELabel = new javax.swing.JLabel();
        epochProgressBar = new javax.swing.JProgressBar();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        chartContainerPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chartContainerPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                chartPanelResizeHandler(evt);
            }
        });

        javax.swing.GroupLayout chartContainerPanelLayout = new javax.swing.GroupLayout(chartContainerPanel);
        chartContainerPanel.setLayout(chartContainerPanelLayout);
        chartContainerPanelLayout.setHorizontalGroup(
            chartContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        chartContainerPanelLayout.setVerticalGroup(
            chartContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 304, Short.MAX_VALUE)
        );

        trainingPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        trainingPanel.setPreferredSize(new java.awt.Dimension(180, 114));

        netFileNameText.setText("Network");
        netFileNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                netFileNameTextActionPerformed(evt);
            }
        });

        jLabel1.setText("Network File Name");

        autoSaveNetCheck.setSelected(true);
        autoSaveNetCheck.setText("Auto Save");
        autoSaveNetCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoSaveNetCheckActionPerformed(evt);
            }
        });

        saveNetButton.setText("Save Network");
        saveNetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveNetButtonActionPerformed(evt);
            }
        });

        startStopTrain.setText("Start/Stop Training");
        startStopTrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startStopTrainActionPerformed(evt);
            }
        });

        maxNumEpochText.setText("-1");
        maxNumEpochText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxNumEpochTextActionPerformed(evt);
            }
        });

        jLabel6.setText("Max Num. Epochs");

        javax.swing.GroupLayout trainingPanelLayout = new javax.swing.GroupLayout(trainingPanel);
        trainingPanel.setLayout(trainingPanelLayout);
        trainingPanelLayout.setHorizontalGroup(
            trainingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trainingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(trainingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(startStopTrain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(trainingPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(netFileNameText))
                    .addGroup(trainingPanelLayout.createSequentialGroup()
                        .addGroup(trainingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(saveNetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(trainingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(trainingPanelLayout.createSequentialGroup()
                                .addComponent(autoSaveNetCheck)
                                .addGap(0, 11, Short.MAX_VALUE))
                            .addComponent(maxNumEpochText))))
                .addContainerGap())
        );
        trainingPanelLayout.setVerticalGroup(
            trainingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trainingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(trainingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(netFileNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(trainingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(autoSaveNetCheck)
                    .addComponent(saveNetButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(trainingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxNumEpochText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startStopTrain)
                .addContainerGap())
        );

        learningParamsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        learningRateText.setText("0.001");
        learningRateText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                learningRateTextActionPerformed(evt);
            }
        });

        jLabel2.setText("Learning Rate");

        momentumText.setText("0");

        jLabel3.setText("Momentum");

        weightDecayText.setText("0");
        weightDecayText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightDecayTextActionPerformed(evt);
            }
        });

        jLabel4.setText("Weight Decay");

        changeLearningParamsButton.setText("Change Learning Parameters");
        changeLearningParamsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeLearningParamsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout learningParamsPanelLayout = new javax.swing.GroupLayout(learningParamsPanel);
        learningParamsPanel.setLayout(learningParamsPanelLayout);
        learningParamsPanelLayout.setHorizontalGroup(
            learningParamsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(learningParamsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(learningParamsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(changeLearningParamsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addGroup(learningParamsPanelLayout.createSequentialGroup()
                        .addGroup(learningParamsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(learningParamsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(learningParamsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(momentumText)
                            .addComponent(learningRateText)
                            .addComponent(weightDecayText))))
                .addContainerGap())
        );
        learningParamsPanelLayout.setVerticalGroup(
            learningParamsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(learningParamsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(learningParamsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(learningRateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(learningParamsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(momentumText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(learningParamsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weightDecayText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(changeLearningParamsButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        statusPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setText("Epoch Number: ");

        epochNumLabel.setText("0");

        jLabel8.setText("Last MSE: ");

        lastMSELabel.setText("0");

        jLabel10.setText("Epoch Progress");

        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(epochProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addGroup(statusPanelLayout.createSequentialGroup()
                        .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(statusPanelLayout.createSequentialGroup()
                                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lastMSELabel)
                                    .addComponent(epochNumLabel)))
                            .addComponent(jLabel10))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(epochNumLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lastMSELabel))
                .addGap(4, 4, 4)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(epochProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chartContainerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(trainingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(learningParamsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(statusPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chartContainerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(trainingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(learningParamsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(statusPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void autoSaveNetCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoSaveNetCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_autoSaveNetCheckActionPerformed

    private void netFileNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_netFileNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_netFileNameTextActionPerformed

    private void saveNetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveNetButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveNetButtonActionPerformed

    private void learningRateTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_learningRateTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_learningRateTextActionPerformed

    private void weightDecayTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightDecayTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weightDecayTextActionPerformed

    private void maxNumEpochTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxNumEpochTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maxNumEpochTextActionPerformed

    private void startStopTrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startStopTrainActionPerformed
        add(i++,Math.random());
    }//GEN-LAST:event_startStopTrainActionPerformed

    private void changeLearningParamsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeLearningParamsButtonActionPerformed
        epochProgressBar.setValue(70);
    }//GEN-LAST:event_changeLearningParamsButtonActionPerformed

    private void chartPanelResizeHandler(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_chartPanelResizeHandler
        chartPanel.setSize(chartContainerPanel.getWidth(), chartContainerPanel.getHeight());
    }//GEN-LAST:event_chartPanelResizeHandler

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrainingJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrainingJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrainingJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrainingJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrainingJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox autoSaveNetCheck;
    private javax.swing.JButton changeLearningParamsButton;
    private javax.swing.JPanel chartContainerPanel;
    private javax.swing.JLabel epochNumLabel;
    private javax.swing.JProgressBar epochProgressBar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lastMSELabel;
    private javax.swing.JPanel learningParamsPanel;
    private javax.swing.JTextField learningRateText;
    private javax.swing.JTextField maxNumEpochText;
    private javax.swing.JTextField momentumText;
    private javax.swing.JTextField netFileNameText;
    private javax.swing.JButton saveNetButton;
    private javax.swing.JButton startStopTrain;
    private javax.swing.JPanel statusPanel;
    private javax.swing.JPanel trainingPanel;
    private javax.swing.JTextField weightDecayText;
    // End of variables declaration//GEN-END:variables
}
